<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 Markus Fischer <markus@fischer.name>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
namespace Mfn\PHP\Reflection\Generator\Listener;

use Mfn\PHP\Reflection\Generator\Reflector;

class Directory implements Listener {

  /**
   * Directory to write per-extension generated reflection data too
   * @var \SplFileInfo
   */
  private $directory;
  /**
   * Collect reflection data per extension
   * Key is the extension name, value is the collected reflection data
   * @var string[]
   */
  private $extension = [];

  public function __construct($directory) {
    if (!($directory instanceof \SplFileInfo)) {
      $directory = new \SplFileInfo($directory);
    }
    $this->setDirectory($directory);
  }

  /**
   * Called before generating starts
   */
  public function beforeGenerate() {
    // TODO: Implement beforeGenerate() method.
  }

  /**
   * Called for every reflected function
   *
   * @param \ReflectionFunction $function
   * @param string $generated
   * @param $generated
   */
  public function generateFunction(\ReflectionFunction $function, $generated) {
    $this->addToExtension($function->getExtensionName(), $generated);
  }

  /**
   * @param string $extension
   * @param string $generated
   */
  private function addToExtension($extension, $generated) {
    if (!isset($this->extension[$extension])) {
      $version = Reflector::VERSION;
      $phpVersion = phpversion();
      $extVersion = phpversion($extension);
      if (false === $extVersion) {
        $extVersion = '';
      } else {
        $extVersion = ' ' . $extVersion;
      }
      $this->extension[$extension] = <<<HEADER
<?php
# Generated by mfn/php-reflection-gen $version
# PHP version $phpVersion, extension $extension$extVersion

HEADER;
    }
    $this->extension[$extension] .= $generated;
  }

  /**
   * Called for every reflected class, interface or trait
   *
   * @param \ReflectionClass $class
   * @param string $generated
   * @param $generated
   */
  public function generateClass(\ReflectionClass $class, $generated) {
    $this->addToExtension($class->getExtensionName(), $generated);
  }

  /**
   * Called when generating is finished
   */
  public function afterGenerate() {
    foreach ($this->extension as $name => $generated) {
      file_put_contents(
        $this->directory->getRealPath() . DIRECTORY_SEPARATOR . $name . '.php',
        $generated
      );
    }
  }

  /**
   * @return string
   */
  public function getDirectory() {
    return $this->directory;
  }

  /**
   * @param \SplFileInfo $directory
   * @return $this
   */
  public function setDirectory(\SplFileInfo $directory) {
    if (!$directory->isDir()) {
      throw new \RuntimeException(
        'Provided file ' . $directory->getRealPath() . ' not a directory'
      );
    }
    $this->directory = $directory;
    return $this;
  }
}
